---

- name: DB.POSTGRES | Prepare deployment
  include_role:
    name: docker.deployment.prepare
    public: "yes"
  vars:
    deployment_name: "{{ postgres.deployment_name }}"
  tags:
    - postgres

- name: DB.POSTGRES | Merge commandline agruments
  set_fact:
    postgres__command: "{{ postgres__command_default + postgres.command_custom }}"
  tags:
    - postgres

- name: DB.POSTGRES | Copy templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ docker_deployment__deploy_path }}/{{ item }}"
  with_items:
    - docker-compose.yml
    - backup.env
  become_user: "{{ docker_deployment__deploy_user_name }}"
  become: yes
  tags:
    - files
    - postgres

- name: DB.POSTGRES | Run deployment
  docker_service:
    project_src: "{{ docker_deployment__deploy_path }}"
    restarted: "yes"
  become: yes
  become_user: "{{ docker_deployment__deploy_user_name }}"
  tags:
    - run
    - postgres
