alertmanager_telegram__image_name: "dhub.touchin.ru/common/alertmanager-telegram"
alertmanager_telegram__image_tag: "latest"
alertmanager_telegram__image: "{{ alertmanager_telegram__image_name }}:{{ alertmanager_telegram__image_tag }}"
