---
- name: TEAMCITY.SERVER | Prepare deployment
  include_role:
    name: docker.deployment.prepare
    public: "yes"
  vars:
    deployment_name: teamcity.server
  tags:
    - teamcity.server

- name: TEAMCITY.SERVER | Copy templates
  template:
    src: templates/{{ item }}.j2
    dest: "{{ docker_deployment__deploy_path }}/{{ item }}"
  with_items:
    - docker-compose.yml
    - ldap-mapping.xml
    - ldap-config.properties
  become_user: "{{ docker_deployment__deploy_user_name }}"
  become: yes
  tags:
    - files
    - teamcity.server

- name: TEAMCITY.SERVER | Run deployment
  docker_service:
    restarted: "yes"
    project_src: "{{ docker_deployment__deploy_path }}"
  become: yes
  become_user: "{{ docker_deployment__deploy_user_name }}"
  tags:
    - run
    - teamcity.server
