---
- name: MONITORING.GRAFANA | Prepare deployment
  include_role:
    name: docker.deployment.prepare
    public: "yes"
  vars:
    deployment_name: grafana
    volume_user: "{{ grafana__user_id }}"
  tags:
    - grafana

- name: MONITORING.GRAFANA | Copy templates
  template:
    src: templates/{{ item }}.j2
    dest: "{{ docker_deployment__deploy_path }}/{{ item }}"
  with_items:
    - docker-compose.yml
  become_user: "{{ docker_deployment__deploy_user_name }}"
  become: yes
  tags:
    - files
    - grafana

- name: MONITORING.GRAFANA | Copy LDAP templates
  template:
    src: templates/{{ item }}.j2
    dest: "{{ docker_deployment__deploy_path }}/{{ item }}"
  with_items:
    - ldap.toml
  become_user: "{{ docker_deployment__deploy_user_name }}"
  become: yes
  when: grafana.ldap is defined and grafana.ldap.enable is defined and grafana.ldap.enable | bool
  tags:
    - files
    - grafana

- name: MONITORING.GRAFANA | Run deployment
  docker_service:
    restarted: "yes"
    project_src: "{{ docker_deployment__deploy_path }}"
  become: yes
  become_user: "{{ docker_deployment__deploy_user_name }}"
  tags:
    - run
    - grafana
